# First of all you must include ode template
# For Gitlab-CI DIOD
include:
  - project: '3cg/3cg_cisco/evita-v12/expect_go'
    ref: 'master'
    file: '/gitlab-ci-golang.yml'
  - project: 'to-be-continuous/custom/dtsi/orange-deployment-engine'
    ref: 'master'
    file: '/templates/gitlab-ci-ode.yml'

variables:
  #Mandatory variables
  ODE_ORANGE_CARTO_ID: "14301"

  # Intégration
  ODE_DEFAULT_INVENTORY: "inventory.yml"
  ODE_PROD_PLAYBOOK: "playbook_CD.yml"
  #Other variables
  ODE_DEFAULT_ARTIFACTS: "expect"
  AUTODEPLOY_TO_PROD : "true"

stages:
  - compile
  - deploy
  - production
