---
- name: Deploy expect to SUPBO
  become: true
  hosts: SUPBO

  tasks:

    - name: Copy executable
      copy:
        src: /home/ansible/delivery/expect
        dest: /opt/nagiosPluginCommand/
        owner: nagiosagent
        grpup: nagiosagent
        mode: '0755'
        force: yes